import type { ToolContent } from "./types";

const content: ToolContent = {
  seoTitle: "PDF Integrity Checker – Validate, Inspect & Detect Signatures Online",
  seoDescription:
    "Check whether a PDF is valid and readable, see its page count, metadata (title, author, creator, dates), form fields and whether it contains a digital signature. Free, private, no upload.",
  intro:
    "Drop a PDF to confirm it opens correctly and to see what's inside without launching a viewer: page count, title, author, creating application, creation and modification dates, whether it contains form fields, and whether a digital signature is present. Useful before sending a document, when a file arrives by email, or when a PDF misbehaves in one app but not another. The file is parsed in your browser and never uploaded.",
  sections: [
    {
      heading: "What the check reports",
      bullets: [
        "Validity — the file is parsed with pdf-lib; if the structure is corrupt, truncated or not actually a PDF, you get an error instead of a report.",
        "Page count — a quick sanity check that a merge or split produced what you expected.",
        "Metadata — Title, Author, Creator (the app that made the content, e.g. Word), Producer (the library that wrote the PDF), and creation/modification dates.",
        "Form fields — whether the document contains interactive AcroForm fields.",
        "Digital signature — detection of signature dictionaries, indicating the PDF has been signed (validity of the signature itself must be checked in Adobe Reader or a signing service).",
      ],
    },
    {
      heading: "Why a PDF might be broken",
      bullets: [
        "Incomplete download or upload — the file is truncated and the cross-reference table at the end is missing.",
        "Wrong extension — an image, Word file or HTML error page saved as .pdf.",
        "Damaged by an email gateway or text-mode FTP transfer that altered bytes.",
        "Generated by a buggy library — pages render in Chrome but fail in Acrobat, or vice versa.",
        "Encrypted with a password the viewer does not have.",
      ],
    },
    {
      heading: "Metadata and privacy",
      paragraphs: [
        "The Author and Creator fields often contain a person's name and the software they used, and the dates reveal when a document was really made. Before sharing a contract, résumé or report externally, check these fields here. If they need changing, most PDF editors and the Edit Bookmarks / Organize PDF tools on EverydayTab rewrite the file, and dedicated metadata editors can blank the fields entirely.",
      ],
    },
  ],
  howTo: [
    { name: "Open the PDF", text: "Drop the file onto the page or click to browse. It is read locally." },
    { name: "Review the report", text: "Validity, page count, metadata, form fields and signature presence are shown immediately." },
    { name: "Act on it", text: "Re-download a corrupt file, fix metadata, or proceed with confidence that the document is intact." },
  ],
  faqs: [
    {
      question: "Does this verify that a digital signature is valid?",
      answer:
        "It detects whether a signature is present. Validating the signature — checking the certificate chain and that the document is unchanged — requires a trusted viewer such as Adobe Acrobat Reader or the signing platform.",
    },
    {
      question: "Can it repair a damaged PDF?",
      answer:
        "No. It reports whether the file parses. If it fails, try re-downloading the original; some corrupt files can be recovered with Ghostscript or qpdf on a desktop.",
    },
    {
      question: "Why does the title show as Untitled?",
      answer: "The document has no Title metadata set. Many PDF generators leave it blank; it does not indicate a problem with the file.",
    },
    {
      question: "Is my PDF uploaded?",
      answer: "No. Parsing happens in your browser; the document never leaves your device.",
    },
  ],
  related: ["compress-pdf", "merge-pdf", "remove-annotations", "edit-bookmarks", "pdf-to-text", "sign-pdf"],
};

export default content;
